// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SabinaFlowerAPI.Data;

#nullable disable

namespace SabinaFlowerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SabinaFlowerAPI.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/Buketlər.jpg",
                            Name = "Bouquets",
                            Slug = "bouquets"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/Kompozisiyalar.jpg",
                            Name = "Compositions",
                            Slug = "compositions"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/category-bridal.jpg",
                            Name = "Bridal Bouquets",
                            Slug = "bridal"
                        });
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Delicate bouquet made with fresh pink roses",
                            ImageUrl = "/images/Çəhrayı romantik güllər.jpg",
                            Name = "Pink Roses Bouquet",
                            Price = 70m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Elegant arrangement of white and blush peonies",
                            ImageUrl = "/images/Ağ və çəhrayı pionlar.jpg",
                            Name = "Peony Arrangement",
                            Price = 85m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Classic bridal bouquet with white roses and eucalyptus",
                            ImageUrl = "/images/Gəlin buketi.jpg",
                            Name = "Classic Bridal Bouquet",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Crafted in a lively palette, this daisy bouquet radiates positivity and refined charm.",
                            ImageUrl = "/images/rengberengpapatyalar.jpg",
                            Name = "Colorful Daisy Bouquet",
                            Price = 60m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Delicate lavender composition in pastel colors",
                            ImageUrl = "/images/Lavanda və zərif vaza kompozisiyası.jpg",
                            Name = "Lavender Flowers",
                            Price = 55m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Bright sunflower and daisy bouquet",
                            ImageUrl = "/images/Günəbaxan.jpg",
                            Name = "Sunflower Bouquet",
                            Price = 60m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Luxury orchid arrangement in glass vase",
                            ImageUrl = "/images/orkideler.jpg",
                            Name = "Orchid Arrangement",
                            Price = 95m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "A refined bouquet of pure white daisies embodying timeless elegance",
                            ImageUrl = "/images/papatyalarbuketi.jpg",
                            Name = "Elegant Daisy Bouquet",
                            Price = 60m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Exquisite bridal bouquet with white peonies",
                            ImageUrl = "/images/gelinpionbuketi.jpg",
                            Name = "Bridal Peony Bouquet",
                            Price = 120m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Special bouquet made with colorful mixed flowers",
                            ImageUrl = "/images/Lalələr.jpg",
                            Name = "Mixed Flower Bouquet",
                            Price = 65m
                        });
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "isgandarova@sabinaflower.az",
                            FullName = "Sebine Isgenderova",
                            PasswordHash = "$2a$11$PM8.k3CkMK6bB9aBT6yU1O0LxyshJTwWhCSoEdJDvqVaz.AcSSvdi",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.BasketItem", b =>
                {
                    b.HasOne("SabinaFlowerAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabinaFlowerAPI.Models.User", "User")
                        .WithMany("BasketItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Order", b =>
                {
                    b.HasOne("SabinaFlowerAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.OrderItem", b =>
                {
                    b.HasOne("SabinaFlowerAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabinaFlowerAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Product", b =>
                {
                    b.HasOne("SabinaFlowerAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.WishlistItem", b =>
                {
                    b.HasOne("SabinaFlowerAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabinaFlowerAPI.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SabinaFlowerAPI.Models.User", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
